apache_admin/urls.py
#from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('apache_admin',

    # ATTENTION! ONLY FOR DEVELOPMENT; NOT FOR PRODUCTION!!!!
#    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/simeon/workspace/django/las3-django/media/'}),

    # public stuff
    url(r'maintenance$', 'views.maintenance'),
    url(r'login$', 'views.login_apache_admin', name='login'),
    url(r'logout$', 'views.logout_apache_admin', name='logout'),
    url(r'password_reset$', 'views.password_reset', name='password_reset'),

    # password protected stuff
    url(r'^$', 'views.home', name='home'),
    url(r'^info', 'views.info'),
    url(r'^projects', 'views.projects'),
    url(r'^usermod/(?P<user_id>\d+)', 'views.usermod', name='usermod'),
    url(r'^emails/(?P<what>.*)/(?P<param>\w+)/(?P<which>\d+)', 'views.emails'),

    # Gods only stuff
    url(r'^config/(?P<which>.+)', 'views.get_config'),
    url(r'^delete/(?P<what>\w+)/(?P<which>\d+)', 'views.delete'),
    url(r'^overview/(?P<what>\w+)$', 'views.overview', name='overview'),
    url(r'^projectadd', 'views.projectadd'),
    url(r'^projectmod/(?P<project_id>\d+)', 'views.projectmod', name='projectmod'),
    url(r'^useradd', 'views.useradd'),
    url(r'^sharemod/(?P<share_id>\d+)', 'views.sharemod', name='sharemod'),
    url(r'^shareadd', 'views.shareadd'),
)

lab_regime/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
        # Apps urls
        url(r'^', include('apache_admin.urls')),
        url(r'^todo/', include('todo.urls')),
        #url(r'^accounts/login/.*$', 'django.contrib.auth.views.login'),
        #url(r'^accounts/logout/.*$', 'django.contrib.auth.views.logout'),
        # Uncomment the admin/doc line below to enable admin documentation:
        # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        # Uncomment the next line to enable the admin:
        url(r'^admin/', include(admin.site.urls)),
)

todo/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
        url(r'^mine/$', 'todo.views.view_list',{'list_slug':'mine'},name="todo-mine"),
        url(r'^mine/wiki/$', 'todo.views.view_list',{'list_slug':'mine', 'wiki': True},name="todo-mine-wiki"),
        url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', 'todo.views.del_list',name="todo-del_list"),
        url(r'^task/(?P<task_id>\d{1,6})$', 'todo.views.view_task', name='todo-task_detail'),
        url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', 'todo.views.view_list', name='todo-incomplete_tasks'),
        url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', 'todo.views.view_list', {'view_completed':1},name='todo-completed_tasks'),
        url(r'^add_list/$', 'todo.views.add_list',name="todo-add_list"),
        #url(r'^search/$', 'todo.views.search',name="todo-search"),    
        url(r'^$', 'todo.views.list_lists',name="todo-lists"),

        ## View reorder_tasks is only called by JQuery for drag/drop task ordering
        url(r'^reorder_tasks/$', 'todo.views.reorder_tasks',name="todo-reorder_tasks"),

        #url(r'^ticket/add/$', 'todo.views.external_add',name="todo-external-add"),    
        #url(r'^recent/added/$', 'todo.views.view_list',{'list_slug':'recent-add'},name="todo-recently_added"),
        #url(r'^recent/completed/$', 'todo.views.view_list',{'list_slug':'recent-complete'},name="todo-recently_completed"),    
)

apache_admin/models.py
import re

from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

# Make strings translatable
from django.utils.translation import ugettext as _

SHARE_TYPE_CHOICES = (
        ('bzr', 'Bazaar'),
        ('git', 'Git'),
        ('svn', 'Subversion'),
        ('dav', 'Wedav Folder'),
        ('wik', 'Wiki'),
)

MEMBER_TYPE_CHOICES = (
        ('master', 'Master Student'),
        ('bachelor', 'Bachelor Student'),
        ('phd', 'PhD Student'),
        ('shk', 'Studentische Hilfskraft'),
        ('prof', 'Professor'),
        ('extern', 'Extern'),
        ('alumni', 'Alumni'),
        ('none', 'Nichts von alldem')
)

class Member(models.Model):

    def __unicode__(self):
        return self.user.last_name + " " + self.user.first_name + " (" + self.get_member_type_display() + ")"

    class Meta:
        ordering = ['user__last_name']
        permissions = (
              #  ("change_member", "Can change member data"),
              #  ("change_username", "Can change the username"),
        )

    user = models.ForeignKey(User, unique = True)
    htdigest = models.CharField(max_length=255)

    begins = models.DateField('access begins', help_text=_("Access to shares starts on this date."))
    expires = models.DateField('access expires', help_text=_("Access to shares expires on this date."))

    projects = models.ManyToManyField('Project', null=True, blank=True)

    member_type = models.CharField(max_length=10, choices=MEMBER_TYPE_CHOICES, default='none')


class Share(models.Model):

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name + " (" + self.get_share_type_display() + ")"

    def clean(self):
        if(re.match(r"^[a-zA-Z0-9_-]+$", self.name)):
            return self.name
        raise ValidationError(_("name may only contain letters, numbers, - and _"))

    name = models.CharField(max_length=40, help_text = _("Only letters, numbers, - and _"))
    share_type = models.CharField(max_length=3, choices=SHARE_TYPE_CHOICES)


class Project(models.Model):
    def __unicode__(self):
        return self.name

    def clean(self):
        if(re.match(r"^[a-zA-Z0-9_-]+$", self.name)):
            return self.name
        raise ValidationError(_("name may only contain letters, numbers, - and _"))

    name         = models.CharField(max_length=40, unique=True, help_text=_("Only letters, numbers, - and _"))
    description  = models.CharField(max_length=255)
    start        = models.DateField('project start', help_text=_("Official date. Does not have influence on access to shares."))
    end          = models.DateField('project end', help_text=_("Official date. Does not have influence on access to shares."))
    shares       = models.ManyToManyField(Share, blank=True, null=True)
    pub_mem      = models.BooleanField(default=False, help_text=_("Members can see each other"))
    allow_alumni = models.BooleanField(default=False, help_text=_("Alumni members can access this project's shares"))

    class Meta:
        ordering = ['name']

apache_admin/views.py
# -*- coding: utf-8 -*-
import os, datetime

# django dependencies
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.core.exceptions import ValidationError, PermissionDenied
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.template import Context, loader, RequestContext
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _

# project dependencies
from apache_admin.models import Project, Share, Member, MEMBER_TYPE_CHOICES, SHARE_TYPE_CHOICES
from apache_admin.forms import MemberModForm, ProjectModForm, ShareModForm, UserAddForm, ProjectAddForm, ShareAddForm, LoginForm, PasswordResetForm
from apache_admin.helpers import get_groups_to_render, get_shares_to_render, check_god, request_apache_reload, get_breadcrums, ejabberd_account_update, set_member_password, EjabberdError, create_apache_htdigest

share_types = [ s[0] for s in SHARE_TYPE_CHOICES ]
admins_emails = [ a[1] for a in settings.ADMINS ]

def login_apache_admin(request):

    if request.method == "POST":

        #form = LoginForm(request.POST)

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if not user is None:
            if user.is_active:
                login(request, user)
                # user is successfully logged in
                return HttpResponseRedirect(reverse('home'))
            else:
                # user is not active
                message = _("Your account is not active any more")
                return render_to_response('login.html',
                        locals(),
                        context_instance=RequestContext(request),
                        )
        else:
            # invalid login
            message = _("Username/password missmatch")
            form = LoginForm()
            return render_to_response('login.html',
                    locals(),
                    context_instance=RequestContext(request),
                    )
    # Handle GET request
    form = LoginForm()
    return render_to_response('login.html',
            locals(),
            context_instance=RequestContext(request),
            )

def logout_apache_admin(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def password_reset(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        if username == "":
            form = PasswordResetForm()
            return render_to_response('password_reset.html',
                    locals(),
                    context_instance=RequestContext(request),
                    )
        try:
            member = Member.objects.get(user__username=username)
            set_member_password(member)
            member.user.save()
            member.save()
        except Member.DoesNotExist:
            pass

        message = _("If your username exists, the new password is sent to the given mail address.")
        return render_to_response('password_reset.html',
                locals(),
                context_instance=RequestContext(request),
                )

    form = PasswordResetForm()
    return render_to_response('password_reset.html',
            locals(),
            context_instance=RequestContext(request),
            )

@login_required(login_url='login')
def home(request):
    global SHARE_TYPE_CHOICES
    global MEMBER_TYPE_CHOICES
    member_types = MEMBER_TYPE_CHOICES
    share_types = SHARE_TYPE_CHOICES
    member_status = [
            {'name': 'active', 'display': _('Aktive')},
            {'name': 'inactive', 'display': _('Inaktive')},
            {'name': 'all', 'display': _('Beides')},
            ]

    try:
        member     = Member.objects.get(user=request.user)
    except Member.DoesNotExist:
        error_admin_logged_in = True
        return render_to_response('home.html',
                locals(),
                context_instance=RequestContext(request),
                )

    projects   = Project.objects.filter(member=member)
    is_god     = check_god(request)
    breadcrums = get_breadcrums(request)

    return render_to_response('home.html',
            locals(),
            context_instance=RequestContext(request),
            )

@login_required(login_url='login')
def info(request):
    is_god = check_god(request)
    breadcrums = get_breadcrums(request)
    return render_to_response('info.html',
            locals(),
            context_instance=RequestContext(request),
            )

@login_required(login_url='login')
def overview(request, what):
    """
    This is for members of group Gods. refer to 'views.projects' for project
    listing of currently logged in member
    """

    is_god = check_god(request)
    if not is_god:
        raise PermissionDenied

    breadcrums = get_breadcrums(request)

    if what == "projects":
        projects = Project.objects.all()
        return render_to_response('overview_projects.html',
                locals(),
                context_instance=RequestContext(request),
                )

    elif what == "shares":
        shares = Share.objects.all()
        return render_to_response('overview_shares.html',
                locals(),
                context_instance=RequestContext(request),
                )

    elif what == "members":
        members = Member.objects.all()
        return render_to_response('overview_members.html',
                locals(),
                context_instance=RequestContext(request),
                )

    elif what == "groups":
        groups = Group.objects.all()
        return render_to_response('overview_groups.html',
                locals(),
                context_instance=RequestContext(request),
                )

    else:
        return HttpResponse("The requested overview " + what + " is not available / implemented")

# No login required!
def maintenance(request):

    if not os.path.isdir(settings.GENERATE_FOLDER):
        os.makedirs(settings.GENERATE_FOLDER)

    # writes configs, updates is_active flag

    def answer(message, error=None):
        return render_to_response("maintenance.html",
                {
                    'error': error,
                    'message': message,
                    'email_problem': email_problem,
                })


    email_problem = False
    disabled_members = []
    enabled_members = []

    # take care about expired users
    for m in Member.objects.filter(user__is_active=True, expires__lt=datetime.date.today()):
        print "The member", m.user, "expired at", m.expires, m.user.first_name, m.user.last_name, "will be set inactive"
        m.user.is_active = False
        m.user.save()
        request_apache_reload()
        disabled_members.append(m)
        mail_body = render_to_string("email/account_expired.txt", {'member': m})
        try:
            sent = send_mail("Account expired", mail_body, admins_emails[0], [admins_emails[0], m.user.email])
        except Exception, e:
            email_problem = True

    # take care about activating users
    for m in Member.objects.filter(user__is_active=False, expires__gte=datetime.date.today()):
        print "The member", m.user, "became active at", m.expires, m.user.first_name, m.user.last_name, "will be activated"
        m.user.is_active = True
        m.user.save()
        request_apache_reload()
        enabled_members.append(m)
        mail_body = render_to_string("email/account_activated.txt", {'member': m})
        try:
            sent = send_mail("Account activated", mail_body, admins_emails[0], [admins_emails[0], m.user.email])
        except Exception, e:
            email_problem = True

    # vcs and dav configs
    share_types = [s[0] for s in SHARE_TYPE_CHOICES]
    for typ in share_types:
        shares = get_shares_to_render(typ)
        for share in shares:
            filename = os.path.join(settings.GENERATE_FOLDER, typ + ".config")
            try:
                with open(filename, "wb") as apache_config_file:
                    apache_config_file.write(render_to_string("configs/" + typ + ".config",
                        {
                            'shares': shares,
                        },))
                    apache_config_file.close()

            except Exception, e:
                error = "Could not write config file " + os.path.abspath(filename) + "\n" + "Exception: " + str(e)
                raise e
                return answer(message=_("There was a problem."), error=error)

    # Apache group file
    filename = os.path.join(settings.GENERATE_FOLDER, "groups.dav")
    groups = get_groups_to_render()
    try:
        with open(filename, "wb") as apache_group_file:
            apache_group_file.write(render_to_string("configs/groups.dav",
                {
                    'groups': groups,
                },))
            apache_group_file.close()
    except Exception, e:
        error = "Could not write config file " + os.path.abspath(filename) + "\n" + "Exception: " + str(e)
        return answer(message=_("There was a problem."), error=error)

    # Apache password file
    filename = os.path.join(settings.GENERATE_FOLDER, "passwd.dav")
    passwd = "\n".join([m.htdigest for m in Member.objects.filter(user__is_active=True)])
    passwd += "\n"
    passwd += "\n".join([m.htdigest for m in Member.objects.filter(user__is_active=False, member_type='alumni')]) 
    passwd += "\n"
    try:
        with open(filename, "wb") as apache_passwd_file:
            apache_passwd_file.write(passwd)
            apache_passwd_file.close()

apache_admin/templates/breadcrums.html
{% block breadcrums %}

{% if breadcrums and not wiki %}

<div class="las3-breadcrums">

    {% for b in breadcrums %}
    <a {% if b.god_required %}class="gods"{% endif %} href="{% url home %}{{ b.url }}">{{ b.name }}</a>
    {% endfor %}

</div>

{% else %}

<!-- No breadcrums available -->

{% endif %}

{% endblock %}

apache_admin/templates/delete.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Delete item{% endblock %}

{% block header %}
{% include "header_javascript.html" %}
{% endblock %}

{% block content %}

{% if error %}
<p class="ui-state-error">Folgende Angaben waren Fehlerhaft:<br />
{{ error }}
</p>
{% endif %}

<div align="center" width="75%" class"ui-state-highlight" style="white-space: nowrap; font-size: 200%;">

    <p class="ui-state-highlight">Aber Hallo! 
    {% if instance.first_name %}
    <strong>Member und user von {{ instance.first_name }} {{ instance.last_name }} ({{ instance }})</strong>
    {% else %}
    <strong>{{ instance }}</strong> 
    {% endif %}
    wirklich löschen?</p>

    <form action="{% url home %}delete/{{ what }}/{{ instance.pk }}" method="POST">
        {% csrf_token %}
        <table width="50%">
        <tr>
            <td align="left"><a class="button" href="{% url home %}{{ what }}/{{ instance.pk }}">Nö</a></td>
            <td align="right"><input type="submit" value="Klar! Lösche!"/></td>
        </tr>
        </table>
    </form>
</div>


{% endblock %}

apache_admin/templates/home.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Start{% endblock %}

{% block title %}
    <h1 align="center">LaS³ Projekte - Start</h1>
{% endblock %}

{% block content %}


    {% if member %}

    <div class="las3-content">

        <div class="member-welcome">
            <h1>Hallo {{ member.user.first_name }}</h1>

            <p>Hier hast du Einblick in Projekte rund ums LaS³.</p>
            <p>Du kannst auch dein <a href="usermod/{{ member.user.pk }}">Profil ändern</a>. Schau auch mal in die <a href="{% url home %}info">info</a>.</p>
        </div>

        <div class="columns">

            <div class="left">
                <h1><a href="{% url home %}projects">Projekte</a></h1>

                <p>Projekte und Freigaben von dir:</p>

                {% for p in projects %}
                <h2><a href="projectmod/{{ p.pk }}">{{ p }}</a></h2>

                {% if p.members.all|length > 0 and p.pub_mem %}
                <p>Andere Projektmitglieder: (<a href="{% url home %}emails/project/active/{{ p.pk }}">E-Mails</a>)</p>
                <ul>
                    {# list of all members, but don't show the visitor himself #}
                    {% for m in p.member_set.all %}
                        {% if m.user.id != request.user.id %}
                            <li>
                                {% if is_god %}
                                <a href="{% url home %}usermod/{{ m.user.pk }}">{{ m.user.get_full_name }}</a>
                                {% else %}
                                    <a href="mailto:{{ m.user.email }}">{{ m.user.get_full_name }}</a>
                                {% endif %}
                                <span style="color: gray;">({{ m.get_member_type_display }})</span>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                {% else %}
                    {% if p.pub_mem %}
                    <p>Keine</p>
                    {% else %}
                    <p>Andere Projektmitglieder nicht einsehbar</p>
                    {% endif %}
                {% endif %}

                {% endfor %}
            </div>

            <div class="left">

                <h1>Aufgaben</h1>

                <p>Aufgaben, aufgeteilt in Listen</p>

                <a href="{% url todo-lists %}">Aufgabenlisten</a>

                <p>Aufgaben, die dir zugewiesen wurden:</p>

                <a style="white-space: nowrap;" href="{% url todo-mine %}">Meine Aufgaben</a>

            </div>

            <div class="left">
                <h1>Gruppen</h1>

                <p>Gruppen, zu denen du gehörst</p>

                <ul>
                    {% for g in member.user.groups.all %}
                    <li>{{ g }}</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="clear"></div>

        </div><!-- columns -->

        {% if is_god %}
        <div class="gods">
            <h1>Administration</h1>
            <p>Du bist einer von 'Gods'. Walte deines Amtes.</p>

            <h2>E-Mail - Adressen</h2>

            <p>Hol dir die E-Mail Adressen von:</p>
            <ul>
                {% for s in member_status %}
                <li><a href="{% url home %}emails/all/{{ s.name }}/0">{{ s.display }}</a> aller Bereiche</li>
                {% endfor %}

                {% for mt in member_types %}
                <li>
                    {% for s in member_status %} <a href="{% url home %}emails/member_type_{{ mt.0 }}/{{ s.name }}/0">{{ s.display }}</a> {% endfor %}
                    in Member Typ {{ mt.1 }}
                </li>
                {% endfor %}

                {% for st in share_types %}
                <li>
                    {% for s in member_status %} <a href="{% url home %}emails/share_type_{{ st.0 }}/{{ s.name }}/0">{{ s.display }}</a> {% endfor %}
                    in Share Typ {{ st.1 }}
                </li>
                {% endfor %}
            </ul>

            <h2>Gesamtübersichten</h2>

            <ul>
                <li><a href="{% url home %}overview/members">Alle Benutzer</a></li>
                <li><a href="{% url home %}overview/projects">Alle Projekte</a></li>
                <li><a href="{% url home %}overview/shares">Alle Freigaben</a></li>
                <li><a href="{% url home %}overview/groups">Alle Gruppen</a></li>
            </ul>

            <h2>Erstellen</h2>

            <ul>
                <li><a href="{% url home %}useradd">Neuer Benutzer</a></li>
                <li><a href="{% url home %}projectadd">Neues Projekt</a></li>
                <li><a href="{% url home %}shareadd">Neue Freigabe</a></li>
            </ul>

            <h2>Konfigurationen</h2>

            <p>Einen Einblick in Konfigurationen für den Webserver, welche regelmäßig generiert werden, gibt es hier:</p>

            <ul>
                <li><a href="{% url home %}config/groups.dav">groups.dav</a></li>
            {% for st in share_types %}
                <li><a href="{% url home %}config/{{ st.0 }}">{{ st.1 }}</a></li>
            {% endfor %}
            </ul>

            <p>Die Konfigurationen können auch <strong>jetzt</strong> neu <a href="{% url home %}maintenance">geschrieben</a> werden.</p>

        </div><!-- gods -->

    </div><!-- contents -->

    {% endif %}{# is_god #}

    {% else %}{# member #}

    {% if error_admin_logged_in %}
    <p>You are probably logged in as different Admin user. Log out first in the <a href="{% url home %}admin">admin view</a>.</p>
    {% else %}
    <p>Irgendwas ist schief gegangen. Evt. ist die django-Datenbank nicht synchron mit der passwd, apache hat noch nicht die neuen configs geladen oder du solltest dich unter django admin abmelden.</p>
    <p>Es kann auch sein dass du dein Passwort neu setzen musst. Benutze das las3-formular dafür (usermod/....)</p>
    {% endif %}

    {% endif %}{# member #}

{% endblock %}

apache_admin/templates/member_projects.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Deine Projekte{% endblock %}

{% block header %}

    {% include "header_javascript.html" %}

{% endblock %}

{% block title %}
    <h1>Projekte bei denen du beteiligt bist</h1>
{% endblock %}

{% block content %}

    {% if projects %}
    {% include 'projects.html' %}
    {% else %}
    <p>Keine Projekte.</p>
    <p>Vielleicht lief etwas schief?</p>
    {% endif %} {# projects #}

{% endblock %}

apache_admin/templates/member_tablerow.html
<tr>
    <td><a href="{% url home %}usermod/{{ member.user.pk }}">{{ member.user.last_name }}</a></td>
    <td><a href="{% url home %}usermod/{{ member.user.pk }}">{{ member.user.first_name }}</a></td>
    <td><a href="{% url home %}usermod/{{ member.user.pk }}">{{ member.user.username }}</a></td>
    <td>{{ member.expires }}</td>
    <td>{{ member.get_member_type_display }}</td>
    <td>{% for project in member.projects.all %}
        <a href="{% url home %}projectmod/{{ project.pk }}">{{ project.name }}</a><br />
        {% endfor %}
    </td>
    <td>
        {% for project in member.projects.all %}
            {% for share in project.shares.all %}
                <a href="{% url home %}sharemod/{{ share.pk }}">{{ share }}</a> <br />
            {% endfor %}
        {% endfor %}
    </td>
</tr>

apache_admin/templates/overview_groups.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Übersicht Gruppen{% endblock %}
{% block header %}

    {% include "header_javascript.html" %}

{% endblock %}

{% block title %}
    <h1>Übersicht aller Gruppen</h1>
{% endblock %}

{% block content %}

    {% if groups %}
    <ul>
    {% for g in groups %}
        <li>{{ g }}</li>
        <ul>
            {% for u in g.user_set.all %}
                {% for m in u.member_set.all %}
                    <li><a href="{% url home %}usermod/{{ m.user.pk }}">{{ m.user.get_full_name }}</a></li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endfor %}
    </ul>


    {% else %}
    <p>I cannot show you any groups.</p>
    <p>Maybe something went wrong</p>
    {% endif %}

{% endblock %}

apache_admin/templates/overview_projects.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Übersicht Projekte{% endblock %}

{% block header %}

    {% include "header_javascript.html" %}

{% endblock %}

{% block title %}
    <h1>Übersicht aller Projekte</h1>
{% endblock %}

{% block content %}

    <p><a class="button" href="{% url home %}projectadd">Projekt hinzufügen</a></p>

    {% include "projects.html" %}

{% endblock %}

apache_admin/templates/overview_shares.html
{% extends "base.html" %}

{% block page_heading %}LaS³ - Übersicht Freigaben{% endblock %}

{% block header %}
{% include "header_javascript.html" %}
{% endblock %}

{% block title %}
    <h1>Überblick aller Freigaben</h1>
{% endblock %}

{% block content %}
<p><a class="button" href="{% url home %}shareadd">Freigabe hinzufügen</a></p>

    {% if shares %}
    <table align="center" border="1" width="75%">
        <tr>
            <th>Name</th><th>Art</th><th>Zugehörige Projekte</th><th>Benutzer</th>
        </tr>
        {% for s in shares %}
        <tr>
            <td><a href="{% url home %}sharemod/{{ s.pk }}">{{ s.name }}</a></td>
            <td>{{ s.get_share_type_display }}</td>
            <td>
                {% if s.project_set.all|length > 0 %}
                    {% for p in s.project_set.all %}
                        <a href="{% url home %}projectmod/{{ p.pk }}">{{ p.name }}</a><br />
                    {% endfor %}
                {% else %}
                No projects related!
                {% endif %}
            </td>
            <td>
                {% for p in s.project_set.all %}
                    {% for m in p.member_set.all %}
                        <span style="whitespace:nowrap;">
                            <a href="{% url home %}usermod/{{ m.user.pk }}">{{ m.user.last_name }} {{ m.user.first_name }}</a>
                            <span style="color: gray;">({{ m.get_member_type_display }})</span>
                        </span>
                        <br />
                    {% endfor %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>I cannot show you any share information at the moment</p>
    <p>Maybe something went wrong</p>
    {% endif %} {# shares #}
{% endblock %}

apache_admin/templates/projectadd.html
{% extends "base.html" %}

{% block header %}

    {% include "header_javascript.html" %}

{% endblock %}

{% block content %}

{% if error %}
<p class="ui-state-error">Folgende Angaben waren Fehlerhaft:
{{ error }}
</p>
{% endif %}

<form action="{% url home %}projectadd" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Add"/>
</form>
{% endblock %}